/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_AALParameters_H_
#define	_AALParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AALParameters */
typedef OCTET_STRING_t	 AALParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AALParameters;
asn_struct_free_f AALParameters_free;
asn_struct_print_f AALParameters_print;
asn_constr_check_f AALParameters_constraint;
ber_type_decoder_f AALParameters_decode_ber;
der_type_encoder_f AALParameters_encode_der;
xer_type_decoder_f AALParameters_decode_xer;
xer_type_encoder_f AALParameters_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AALParameters_H_ */
#include <asn_internal.h>
