/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_AARE_apdu_H_
#define	_AARE_apdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <OBJECT_IDENTIFIER.h>
#include "Associate-result.h"
#include "Associate-source-diagnostic.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum protocol_versionRE {
	protocol_versionRE_version1	= 0
} e_protocol_versionRE;

/* AARE-apdu */
typedef struct AARE_apdu {
	BIT_STRING_t	*protocol_versionRE	/* DEFAULT {version1} */;
	OBJECT_IDENTIFIER_t	 application_context_name;
	Associate_result_t	 result;
	Associate_source_diagnostic_t	 result_source_diagnostic;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AARE_apdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AARE_apdu;

#ifdef __cplusplus
}
#endif

#endif	/* _AARE_apdu_H_ */
#include <asn_internal.h>
