/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_Abort_H_
#define	_Abort_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DestTransactionID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Reason;

/* Abort */
typedef struct Abort {
	DestTransactionID_t	 dtid;
	struct Reason	*reason	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Abort_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Abort;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Reason.h"

#endif	/* _Abort_H_ */
#include <asn_internal.h>
