/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_ABRT_apdu_H_
#define	_ABRT_apdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ABRT-source.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ABRT-apdu */
typedef struct ABRT_apdu {
	ABRT_source_t	 abort_source;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ABRT_apdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ABRT_apdu;

#ifdef __cplusplus
}
#endif

#endif	/* _ABRT_apdu_H_ */
#include <asn_internal.h>
