/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_AdditionalATMCellRate_H_
#define	_AdditionalATMCellRate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AdditionalATMCellRate */
typedef OCTET_STRING_t	 AdditionalATMCellRate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdditionalATMCellRate;
asn_struct_free_f AdditionalATMCellRate_free;
asn_struct_print_f AdditionalATMCellRate_print;
asn_constr_check_f AdditionalATMCellRate_constraint;
ber_type_decoder_f AdditionalATMCellRate_decode_ber;
der_type_encoder_f AdditionalATMCellRate_encode_der;
xer_type_decoder_f AdditionalATMCellRate_decode_xer;
xer_type_encoder_f AdditionalATMCellRate_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AdditionalATMCellRate_H_ */
#include <asn_internal.h>
