/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_AdditionalCallingPartyNumber_H_
#define	_AdditionalCallingPartyNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Digits.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AdditionalCallingPartyNumber */
typedef Digits_t	 AdditionalCallingPartyNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdditionalCallingPartyNumber;
asn_struct_free_f AdditionalCallingPartyNumber_free;
asn_struct_print_f AdditionalCallingPartyNumber_print;
asn_constr_check_f AdditionalCallingPartyNumber_constraint;
ber_type_decoder_f AdditionalCallingPartyNumber_decode_ber;
der_type_encoder_f AdditionalCallingPartyNumber_encode_der;
xer_type_decoder_f AdditionalCallingPartyNumber_decode_xer;
xer_type_encoder_f AdditionalCallingPartyNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AdditionalCallingPartyNumber_H_ */
#include <asn_internal.h>
