/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_AESACallingParty_H_
#define	_AESACallingParty_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AESACallingParty */
typedef OCTET_STRING_t	 AESACallingParty_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AESACallingParty;
asn_struct_free_f AESACallingParty_free;
asn_struct_print_f AESACallingParty_print;
asn_constr_check_f AESACallingParty_constraint;
ber_type_decoder_f AESACallingParty_decode_ber;
der_type_encoder_f AESACallingParty_encode_der;
xer_type_decoder_f AESACallingParty_decode_xer;
xer_type_encoder_f AESACallingParty_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AESACallingParty_H_ */
#include <asn_internal.h>
