/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_AlternativeIdentities_H_
#define	_AlternativeIdentities_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AlternativeIdentity;

/* AlternativeIdentities */
typedef struct AlternativeIdentities {
	A_SEQUENCE_OF(struct AlternativeIdentity) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlternativeIdentities_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlternativeIdentities;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlternativeIdentity.h"

#endif	/* _AlternativeIdentities_H_ */
#include <asn_internal.h>
