/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_BearerCapability_H_
#define	_BearerCapability_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BearerCapability_PR {
	BearerCapability_PR_NOTHING,	/* No components present */
	BearerCapability_PR_bearerCap,
	BearerCapability_PR_tmr,
	BearerCapability_PR_broadbandBearerCap
} BearerCapability_PR;

/* BearerCapability */
typedef struct BearerCapability {
	BearerCapability_PR present;
	union BearerCapability_u {
		OCTET_STRING_t	 bearerCap;
		OCTET_STRING_t	 tmr;
		OCTET_STRING_t	 broadbandBearerCap;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BearerCapability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BearerCapability;

#ifdef __cplusplus
}
#endif

#endif	/* _BearerCapability_H_ */
#include <asn_internal.h>
