/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#include "BISDNParameters.h"

static asn_TYPE_member_t asn_MBR_BISDNParameters_1[] = {
	{ ATF_POINTER, 10, offsetof(struct BISDNParameters, aALParameters),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AALParameters,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aALParameters"
		},
	{ ATF_POINTER, 9, offsetof(struct BISDNParameters, additionalATMCellRate),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AdditionalATMCellRate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"additionalATMCellRate"
		},
	{ ATF_POINTER, 8, offsetof(struct BISDNParameters, aESACalledParty),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AESACalledParty,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aESACalledParty"
		},
	{ ATF_POINTER, 7, offsetof(struct BISDNParameters, aESACallingParty),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AESACallingParty,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aESACallingParty"
		},
	{ ATF_POINTER, 6, offsetof(struct BISDNParameters, alternativeATMTrafficDescriptor),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AlternativeATMTrafficDescriptor,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alternativeATMTrafficDescriptor"
		},
	{ ATF_POINTER, 5, offsetof(struct BISDNParameters, aTMCellRate),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ATMCellRate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aTMCellRate"
		},
	{ ATF_POINTER, 4, offsetof(struct BISDNParameters, cDVTDescriptor),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CDVTDescriptor,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cDVTDescriptor"
		},
	{ ATF_POINTER, 3, offsetof(struct BISDNParameters, cumulativeTransitDelay),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CumulativeTransitDelay,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cumulativeTransitDelay"
		},
	{ ATF_POINTER, 2, offsetof(struct BISDNParameters, endToEndTransitDelay),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_EndToEndTransitDelay,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"endToEndTransitDelay"
		},
	{ ATF_POINTER, 1, offsetof(struct BISDNParameters, minAcceptableATMTrafficDescriptor),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MinAcceptableATMTrafficDescriptor,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"minAcceptableATMTrafficDescriptor"
		},
};
static ber_tlv_tag_t asn_DEF_BISDNParameters_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_BISDNParameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* aALParameters at 502 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* additionalATMCellRate at 503 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* aESACalledParty at 504 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* aESACallingParty at 505 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* alternativeATMTrafficDescriptor at 507 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* aTMCellRate at 508 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* cDVTDescriptor at 509 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* cumulativeTransitDelay at 510 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* endToEndTransitDelay at 511 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* minAcceptableATMTrafficDescriptor at 513 */
};
static asn_SEQUENCE_specifics_t asn_SPC_BISDNParameters_specs_1 = {
	sizeof(struct BISDNParameters),
	offsetof(struct BISDNParameters, _asn_ctx),
	asn_MAP_BISDNParameters_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	9,	/* Start extensions */
	11	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BISDNParameters = {
	"BISDNParameters",
	"BISDNParameters",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BISDNParameters_tags_1,
	sizeof(asn_DEF_BISDNParameters_tags_1)
		/sizeof(asn_DEF_BISDNParameters_tags_1[0]), /* 1 */
	asn_DEF_BISDNParameters_tags_1,	/* Same as above */
	sizeof(asn_DEF_BISDNParameters_tags_1)
		/sizeof(asn_DEF_BISDNParameters_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_BISDNParameters_1,
	10,	/* Elements count */
	&asn_SPC_BISDNParameters_specs_1	/* Additional specs */
};

