/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_CallingPartysCategory_H_
#define	_CallingPartysCategory_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CallingPartysCategory */
typedef OCTET_STRING_t	 CallingPartysCategory_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallingPartysCategory;
asn_struct_free_f CallingPartysCategory_free;
asn_struct_print_f CallingPartysCategory_print;
asn_constr_check_f CallingPartysCategory_constraint;
ber_type_decoder_f CallingPartysCategory_decode_ber;
der_type_encoder_f CallingPartysCategory_encode_der;
xer_type_decoder_f CallingPartysCategory_decode_xer;
xer_type_encoder_f CallingPartysCategory_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CallingPartysCategory_H_ */
#include <asn_internal.h>
