/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_CallSegmentID_H_
#define	_CallSegmentID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CallSegmentID */
typedef long	 CallSegmentID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallSegmentID;
asn_struct_free_f CallSegmentID_free;
asn_struct_print_f CallSegmentID_print;
asn_constr_check_f CallSegmentID_constraint;
ber_type_decoder_f CallSegmentID_decode_ber;
der_type_encoder_f CallSegmentID_encode_der;
xer_type_decoder_f CallSegmentID_decode_xer;
xer_type_encoder_f CallSegmentID_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CallSegmentID_H_ */
#include <asn_internal.h>
