/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_CalledPartySubaddress_H_
#define	_CalledPartySubaddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CalledPartySubaddress */
typedef OCTET_STRING_t	 CalledPartySubaddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CalledPartySubaddress;
asn_struct_free_f CalledPartySubaddress_free;
asn_struct_print_f CalledPartySubaddress_print;
asn_constr_check_f CalledPartySubaddress_constraint;
ber_type_decoder_f CalledPartySubaddress_decode_ber;
der_type_encoder_f CalledPartySubaddress_encode_der;
xer_type_decoder_f CalledPartySubaddress_decode_xer;
xer_type_encoder_f CalledPartySubaddress_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CalledPartySubaddress_H_ */
#include <asn_internal.h>
