/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_CalledDirectoryNumber_H_
#define	_CalledDirectoryNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CalledDirectoryNumber */
typedef OCTET_STRING_t	 CalledDirectoryNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CalledDirectoryNumber;
asn_struct_free_f CalledDirectoryNumber_free;
asn_struct_print_f CalledDirectoryNumber_print;
asn_constr_check_f CalledDirectoryNumber_constraint;
ber_type_decoder_f CalledDirectoryNumber_decode_ber;
der_type_encoder_f CalledDirectoryNumber_encode_der;
xer_type_decoder_f CalledDirectoryNumber_decode_xer;
xer_type_encoder_f CalledDirectoryNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CalledDirectoryNumber_H_ */
#include <asn_internal.h>
