/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_CalledPartyNumber_H_
#define	_CalledPartyNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CalledPartyNumber */
typedef OCTET_STRING_t	 CalledPartyNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CalledPartyNumber;
asn_struct_free_f CalledPartyNumber_free;
asn_struct_print_f CalledPartyNumber_print;
asn_constr_check_f CalledPartyNumber_constraint;
ber_type_decoder_f CalledPartyNumber_decode_ber;
der_type_encoder_f CalledPartyNumber_encode_der;
xer_type_decoder_f CalledPartyNumber_decode_xer;
xer_type_encoder_f CalledPartyNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CalledPartyNumber_H_ */
#include <asn_internal.h>
