/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_Carrier_H_
#define	_Carrier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Carrier */
typedef OCTET_STRING_t	 Carrier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Carrier;
asn_struct_free_f Carrier_free;
asn_struct_print_f Carrier_print;
asn_constr_check_f Carrier_constraint;
ber_type_decoder_f Carrier_decode_ber;
der_type_encoder_f Carrier_encode_der;
xer_type_decoder_f Carrier_decode_xer;
xer_type_encoder_f Carrier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Carrier_H_ */
#include <asn_internal.h>
