/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_Cause_H_
#define	_Cause_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Cause */
typedef OCTET_STRING_t	 Cause_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Cause;
asn_struct_free_f Cause_free;
asn_struct_print_f Cause_print;
asn_constr_check_f Cause_constraint;
ber_type_decoder_f Cause_decode_ber;
der_type_encoder_f Cause_encode_der;
xer_type_decoder_f Cause_decode_xer;
xer_type_encoder_f Cause_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Cause_H_ */
#include <asn_internal.h>
