/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_ChargeNumber_H_
#define	_ChargeNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LocationNumber.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ChargeNumber */
typedef LocationNumber_t	 ChargeNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChargeNumber;
asn_struct_free_f ChargeNumber_free;
asn_struct_print_f ChargeNumber_print;
asn_constr_check_f ChargeNumber_constraint;
ber_type_decoder_f ChargeNumber_decode_ber;
der_type_encoder_f ChargeNumber_encode_der;
xer_type_decoder_f ChargeNumber_decode_xer;
xer_type_encoder_f ChargeNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ChargeNumber_H_ */
#include <asn_internal.h>
