/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_ComponentType_H_
#define	_ComponentType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ComponentType {
	ComponentType_any	= 0,
	ComponentType_invoke	= 1,
	ComponentType_rResult	= 2,
	ComponentType_rError	= 3,
	ComponentType_rReject	= 4
} e_ComponentType;

/* ComponentType */
typedef ENUMERATED_t	 ComponentType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ComponentType;
asn_struct_free_f ComponentType_free;
asn_struct_print_f ComponentType_print;
asn_constr_check_f ComponentType_constraint;
ber_type_decoder_f ComponentType_decode_ber;
der_type_encoder_f ComponentType_encode_der;
xer_type_decoder_f ComponentType_decode_xer;
xer_type_encoder_f ComponentType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ComponentType_H_ */
#include <asn_internal.h>
