/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_ComponentCorrelationID_H_
#define	_ComponentCorrelationID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ComponentCorrelationID */
typedef INTEGER_t	 ComponentCorrelationID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ComponentCorrelationID;
asn_struct_free_f ComponentCorrelationID_free;
asn_struct_print_f ComponentCorrelationID_print;
asn_constr_check_f ComponentCorrelationID_constraint;
ber_type_decoder_f ComponentCorrelationID_decode_ber;
der_type_encoder_f ComponentCorrelationID_encode_der;
xer_type_decoder_f ComponentCorrelationID_decode_xer;
xer_type_encoder_f ComponentCorrelationID_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ComponentCorrelationID_H_ */
#include <asn_internal.h>
