/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_ConnectedNumberTreatmentInd_H_
#define	_ConnectedNumberTreatmentInd_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConnectedNumberTreatmentInd {
	ConnectedNumberTreatmentInd_noINImpact	= 0,
	ConnectedNumberTreatmentInd_presentationRestricted	= 1,
	ConnectedNumberTreatmentInd_presentCalledINNumber	= 2,
	ConnectedNumberTreatmentInd_presentCalledINNumberRestricted	= 3
} e_ConnectedNumberTreatmentInd;

/* ConnectedNumberTreatmentInd */
typedef ENUMERATED_t	 ConnectedNumberTreatmentInd_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConnectedNumberTreatmentInd;
asn_struct_free_f ConnectedNumberTreatmentInd_free;
asn_struct_print_f ConnectedNumberTreatmentInd_print;
asn_constr_check_f ConnectedNumberTreatmentInd_constraint;
ber_type_decoder_f ConnectedNumberTreatmentInd_decode_ber;
der_type_encoder_f ConnectedNumberTreatmentInd_encode_der;
xer_type_decoder_f ConnectedNumberTreatmentInd_decode_xer;
xer_type_encoder_f ConnectedNumberTreatmentInd_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ConnectedNumberTreatmentInd_H_ */
#include <asn_internal.h>
