/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#include "ConnectArg.h"

static asn_TYPE_member_t asn_MBR_ConnectArg_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ConnectArg, destinationRoutingAddress),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DestinationRoutingAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"destinationRoutingAddress"
		},
	{ ATF_POINTER, 36, offsetof(struct ConnectArg, alertingPattern),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AlertingPattern,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alertingPattern"
		},
	{ ATF_POINTER, 35, offsetof(struct ConnectArg, correlationID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CorrelationID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"correlationID"
		},
	{ ATF_POINTER, 34, offsetof(struct ConnectArg, cutAndPaste),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CutAndPaste,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cutAndPaste"
		},
	{ ATF_POINTER, 33, offsetof(struct ConnectArg, forwardingCondition),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ForwardingCondition,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"forwardingCondition"
		},
	{ ATF_POINTER, 32, offsetof(struct ConnectArg, iSDNAccessRelatedInformation),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ISDNAccessRelatedInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iSDNAccessRelatedInformation"
		},
	{ ATF_POINTER, 31, offsetof(struct ConnectArg, originalCalledPartyID),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OriginalCalledPartyID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"originalCalledPartyID"
		},
	{ ATF_POINTER, 30, offsetof(struct ConnectArg, routeList),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RouteList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"routeList"
		},
	{ ATF_POINTER, 29, offsetof(struct ConnectArg, scfID),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ScfID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"scfID"
		},
	{ ATF_POINTER, 28, offsetof(struct ConnectArg, travellingClassMark),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TravellingClassMark,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"travellingClassMark"
		},
	{ ATF_POINTER, 27, offsetof(struct ConnectArg, carrier),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Carrier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"carrier"
		},
	{ ATF_POINTER, 26, offsetof(struct ConnectArg, serviceInteractionIndicators),
		(ASN_TAG_CLASS_CONTEXT | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServiceInteractionIndicators,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serviceInteractionIndicators"
		},
	{ ATF_POINTER, 25, offsetof(struct ConnectArg, callingPartyNumber),
		(ASN_TAG_CLASS_CONTEXT | (27 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CallingPartyNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callingPartyNumber"
		},
	{ ATF_POINTER, 24, offsetof(struct ConnectArg, callingPartysCategory),
		(ASN_TAG_CLASS_CONTEXT | (28 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CallingPartysCategory,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callingPartysCategory"
		},
	{ ATF_POINTER, 23, offsetof(struct ConnectArg, redirectingPartyID),
		(ASN_TAG_CLASS_CONTEXT | (29 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RedirectingPartyID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"redirectingPartyID"
		},
	{ ATF_POINTER, 22, offsetof(struct ConnectArg, redirectionInformation),
		(ASN_TAG_CLASS_CONTEXT | (30 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RedirectionInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"redirectionInformation"
		},
	{ ATF_POINTER, 21, offsetof(struct ConnectArg, displayInformation),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DisplayInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"displayInformation"
		},
	{ ATF_POINTER, 20, offsetof(struct ConnectArg, forwardCallIndicators),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ForwardCallIndicators,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"forwardCallIndicators"
		},
	{ ATF_POINTER, 19, offsetof(struct ConnectArg, genericNumbers),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GenericNumbers,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"genericNumbers"
		},
	{ ATF_POINTER, 18, offsetof(struct ConnectArg, serviceInteractionIndicatorsTwo),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServiceInteractionIndicatorsTwo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serviceInteractionIndicatorsTwo"
		},
	{ ATF_POINTER, 17, offsetof(struct ConnectArg, iNServiceCompatibilityResponse),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_INServiceCompatibilityResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iNServiceCompatibilityResponse"
		},
	{ ATF_POINTER, 16, offsetof(struct ConnectArg, forwardGVNS),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ForwardGVNS,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"forwardGVNS"
		},
	{ ATF_POINTER, 15, offsetof(struct ConnectArg, backwardGVNS),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BackwardGVNS,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"backwardGVNS"
		},
	{ ATF_POINTER, 14, offsetof(struct ConnectArg, chargeNumber),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChargeNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"chargeNumber"
		},
	{ ATF_POINTER, 13, offsetof(struct ConnectArg, callSegmentID),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CallSegmentID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callSegmentID"
		},
	{ ATF_POINTER, 12, offsetof(struct ConnectArg, legToBeCreated),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_LegID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"legToBeCreated"
		},
	{ ATF_POINTER, 11, offsetof(struct ConnectArg, sDSSinformation),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SDSSinformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sDSSinformation"
		},
	{ ATF_POINTER, 10, offsetof(struct ConnectArg, calledDirectoryNumber),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CalledDirectoryNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"calledDirectoryNumber"
		},
	{ ATF_POINTER, 9, offsetof(struct ConnectArg, bearerCapability),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_BearerCapability,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bearerCapability"
		},
	{ ATF_POINTER, 8, offsetof(struct ConnectArg, calledPartySubaddress),
		(ASN_TAG_CLASS_CONTEXT | (60 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CalledPartySubaddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"calledPartySubaddress"
		},
	{ ATF_POINTER, 7, offsetof(struct ConnectArg, connectionIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (61 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ConnectionIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"connectionIdentifier"
		},
	{ ATF_POINTER, 6, offsetof(struct ConnectArg, genericIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (62 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GenericIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"genericIdentifier"
		},
	{ ATF_POINTER, 5, offsetof(struct ConnectArg, qOSParameter),
		(ASN_TAG_CLASS_CONTEXT | (63 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QoSParameter,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"qOSParameter"
		},
	{ ATF_POINTER, 4, offsetof(struct ConnectArg, bISDNParameters),
		(ASN_TAG_CLASS_CONTEXT | (64 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BISDNParameters,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bISDNParameters"
		},
	{ ATF_POINTER, 3, offsetof(struct ConnectArg, cug_Interlock),
		(ASN_TAG_CLASS_CONTEXT | (31 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CUG_Interlock,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cug-Interlock"
		},
	{ ATF_POINTER, 2, offsetof(struct ConnectArg, cug_OutgoingAccess),
		(ASN_TAG_CLASS_CONTEXT | (32 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cug-OutgoingAccess"
		},
	{ ATF_POINTER, 1, offsetof(struct ConnectArg, ipRelatedInformation),
		(ASN_TAG_CLASS_CONTEXT | (33 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IPRelatedInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ipRelatedInformation"
		},
};
static ber_tlv_tag_t asn_DEF_ConnectArg_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ConnectArg_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* destinationRoutingAddress at 546 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* alertingPattern at 547 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* correlationID at 548 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* cutAndPaste at 549 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* forwardingCondition at 550 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* iSDNAccessRelatedInformation at 552 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* originalCalledPartyID at 553 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* routeList at 554 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* scfID at 556 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* travellingClassMark at 557 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 10, 0, 0 }, /* carrier at 559 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 16, 0, 0 }, /* displayInformation at 566 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 17, 0, 0 }, /* forwardCallIndicators at 567 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 18, 0, 0 }, /* genericNumbers at 568 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 19, 0, 0 }, /* serviceInteractionIndicatorsTwo at 570 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 20, 0, 0 }, /* iNServiceCompatibilityResponse at 572 */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 21, 0, 0 }, /* forwardGVNS at 573 */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 22, 0, 0 }, /* backwardGVNS at 574 */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 23, 0, 0 }, /* chargeNumber at 575 */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 24, 0, 0 }, /* callSegmentID at 576 */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 25, 0, 0 }, /* legToBeCreated at 577 */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 26, 0, 0 }, /* sDSSinformation at 578 */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 27, 0, 0 }, /* calledDirectoryNumber at 579 */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 28, 0, 0 }, /* bearerCapability at 580 */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 11, 0, 0 }, /* serviceInteractionIndicators at 561 */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 12, 0, 0 }, /* callingPartyNumber at 562 */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 13, 0, 0 }, /* callingPartysCategory at 563 */
    { (ASN_TAG_CLASS_CONTEXT | (29 << 2)), 14, 0, 0 }, /* redirectingPartyID at 564 */
    { (ASN_TAG_CLASS_CONTEXT | (30 << 2)), 15, 0, 0 }, /* redirectionInformation at 565 */
    { (ASN_TAG_CLASS_CONTEXT | (31 << 2)), 34, 0, 0 }, /* cug-Interlock at 587 */
    { (ASN_TAG_CLASS_CONTEXT | (32 << 2)), 35, 0, 0 }, /* cug-OutgoingAccess at 588 */
    { (ASN_TAG_CLASS_CONTEXT | (33 << 2)), 36, 0, 0 }, /* ipRelatedInformation at 589 */
    { (ASN_TAG_CLASS_CONTEXT | (60 << 2)), 29, 0, 0 }, /* calledPartySubaddress at 581 */
    { (ASN_TAG_CLASS_CONTEXT | (61 << 2)), 30, 0, 0 }, /* connectionIdentifier at 582 */
    { (ASN_TAG_CLASS_CONTEXT | (62 << 2)), 31, 0, 0 }, /* genericIdentifier at 583 */
    { (ASN_TAG_CLASS_CONTEXT | (63 << 2)), 32, 0, 0 }, /* qOSParameter at 584 */
    { (ASN_TAG_CLASS_CONTEXT | (64 << 2)), 33, 0, 0 } /* bISDNParameters at 585 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ConnectArg_specs_1 = {
	sizeof(struct ConnectArg),
	offsetof(struct ConnectArg, _asn_ctx),
	asn_MAP_ConnectArg_tag2el_1,
	37,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	33,	/* Start extensions */
	38	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ConnectArg = {
	"ConnectArg",
	"ConnectArg",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ConnectArg_tags_1,
	sizeof(asn_DEF_ConnectArg_tags_1)
		/sizeof(asn_DEF_ConnectArg_tags_1[0]), /* 1 */
	asn_DEF_ConnectArg_tags_1,	/* Same as above */
	sizeof(asn_DEF_ConnectArg_tags_1)
		/sizeof(asn_DEF_ConnectArg_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ConnectArg_1,
	37,	/* Elements count */
	&asn_SPC_ConnectArg_specs_1	/* Additional specs */
};

