/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_CSAID_H_
#define	_CSAID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CSAID */
typedef long	 CSAID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CSAID;
asn_struct_free_f CSAID_free;
asn_struct_print_f CSAID_print;
asn_constr_check_f CSAID_constraint;
ber_type_decoder_f CSAID_decode_ber;
der_type_encoder_f CSAID_encode_der;
xer_type_decoder_f CSAID_decode_xer;
xer_type_encoder_f CSAID_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CSAID_H_ */
#include <asn_internal.h>
