/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_CutAndPaste_H_
#define	_CutAndPaste_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CutAndPaste */
typedef long	 CutAndPaste_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CutAndPaste;
asn_struct_free_f CutAndPaste_free;
asn_struct_print_f CutAndPaste_print;
asn_constr_check_f CutAndPaste_constraint;
ber_type_decoder_f CutAndPaste_decode_ber;
der_type_encoder_f CutAndPaste_encode_der;
xer_type_decoder_f CutAndPaste_decode_xer;
xer_type_encoder_f CutAndPaste_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CutAndPaste_H_ */
#include <asn_internal.h>
