/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_DestinationRoutingAddress_H_
#define	_DestinationRoutingAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CalledPartyNumber.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DestinationRoutingAddress */
typedef struct DestinationRoutingAddress {
	A_SEQUENCE_OF(CalledPartyNumber_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DestinationRoutingAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DestinationRoutingAddress;

#ifdef __cplusplus
}
#endif

#endif	/* _DestinationRoutingAddress_H_ */
#include <asn_internal.h>
