/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#include "Entry.h"

static asn_TYPE_member_t asn_MBR_Entry_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Entry, choice.agreements),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"agreements"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Entry, choice.networkSpecific),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Integer4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"networkSpecific"
		},
};
static asn_TYPE_tag2member_t asn_MAP_Entry_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* agreements at 463 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* networkSpecific at 465 */
};
static asn_CHOICE_specifics_t asn_SPC_Entry_specs_1 = {
	sizeof(struct Entry),
	offsetof(struct Entry, _asn_ctx),
	offsetof(struct Entry, present),
	sizeof(((struct Entry *)0)->present),
	asn_MAP_Entry_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Entry = {
	"Entry",
	"Entry",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_Entry_1,
	2,	/* Elements count */
	&asn_SPC_Entry_specs_1	/* Additional specs */
};

