/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_Entry_H_
#define	_Entry_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include "Integer4.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Entry_PR {
	Entry_PR_NOTHING,	/* No components present */
	Entry_PR_agreements,
	Entry_PR_networkSpecific
} Entry_PR;

/* Entry */
typedef struct Entry {
	Entry_PR present;
	union Entry_u {
		OBJECT_IDENTIFIER_t	 agreements;
		Integer4_t	 networkSpecific;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Entry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Entry;

#ifdef __cplusplus
}
#endif

#endif	/* _Entry_H_ */
#include <asn_internal.h>
