/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_ERROR_H_
#define	_ERROR_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <OBJECT_IDENTIFIER.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ERROR_PR {
	ERROR_PR_NOTHING,	/* No components present */
	ERROR_PR_localValue,
	ERROR_PR_globalValue
} ERROR_PR;

/* ERROR */
typedef struct ERROR {
	ERROR_PR present;
	union ERROR_u {
		INTEGER_t	 localValue;
		OBJECT_IDENTIFIER_t	 globalValue;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ERROR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ERROR;

#ifdef __cplusplus
}
#endif

#endif	/* _ERROR_H_ */
#include <asn_internal.h>
