/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_FCIBillingChargingCharacteristics_H_
#define	_FCIBillingChargingCharacteristics_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FCIBillingChargingCharacteristics */
typedef OCTET_STRING_t	 FCIBillingChargingCharacteristics_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FCIBillingChargingCharacteristics;
asn_struct_free_f FCIBillingChargingCharacteristics_free;
asn_struct_print_f FCIBillingChargingCharacteristics_print;
asn_constr_check_f FCIBillingChargingCharacteristics_constraint;
ber_type_decoder_f FCIBillingChargingCharacteristics_decode_ber;
der_type_encoder_f FCIBillingChargingCharacteristics_encode_der;
xer_type_decoder_f FCIBillingChargingCharacteristics_decode_xer;
xer_type_encoder_f FCIBillingChargingCharacteristics_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _FCIBillingChargingCharacteristics_H_ */
#include <asn_internal.h>
