/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_ForwardServiceInteractionInd_H_
#define	_ForwardServiceInteractionInd_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ForwardServiceInteractionInd */
typedef struct ForwardServiceInteractionInd {
	OCTET_STRING_t	*conferenceTreatmentIndicator	/* OPTIONAL */;
	OCTET_STRING_t	*callDiversionTreatmentIndicator	/* OPTIONAL */;
	OCTET_STRING_t	*callOfferingTreatmentIndicator	/* OPTIONAL */;
	OCTET_STRING_t	*callWaitingTreatmentIndicator	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	OCTET_STRING_t	*holdTreatmentIndicator	/* OPTIONAL */;
	OCTET_STRING_t	*ectTreatmentIndicator	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ForwardServiceInteractionInd_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ForwardServiceInteractionInd;

#ifdef __cplusplus
}
#endif

#endif	/* _ForwardServiceInteractionInd_H_ */
#include <asn_internal.h>
