/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_ForwardCallIndicators_H_
#define	_ForwardCallIndicators_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ForwardCallIndicators */
typedef OCTET_STRING_t	 ForwardCallIndicators_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ForwardCallIndicators;
asn_struct_free_f ForwardCallIndicators_free;
asn_struct_print_f ForwardCallIndicators_print;
asn_constr_check_f ForwardCallIndicators_constraint;
ber_type_decoder_f ForwardCallIndicators_decode_ber;
der_type_encoder_f ForwardCallIndicators_encode_der;
xer_type_decoder_f ForwardCallIndicators_decode_xer;
xer_type_encoder_f ForwardCallIndicators_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ForwardCallIndicators_H_ */
#include <asn_internal.h>
