/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_FurnishChargingInformationArg_H_
#define	_FurnishChargingInformationArg_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FCIBillingChargingCharacteristics.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FurnishChargingInformationArg */
typedef FCIBillingChargingCharacteristics_t	 FurnishChargingInformationArg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FurnishChargingInformationArg;
asn_struct_free_f FurnishChargingInformationArg_free;
asn_struct_print_f FurnishChargingInformationArg_print;
asn_constr_check_f FurnishChargingInformationArg_constraint;
ber_type_decoder_f FurnishChargingInformationArg_decode_ber;
der_type_encoder_f FurnishChargingInformationArg_encode_der;
xer_type_decoder_f FurnishChargingInformationArg_decode_xer;
xer_type_encoder_f FurnishChargingInformationArg_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _FurnishChargingInformationArg_H_ */
#include <asn_internal.h>
