/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_GenericIdentifier_H_
#define	_GenericIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GenericIdentifier */
typedef OCTET_STRING_t	 GenericIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GenericIdentifier;
asn_struct_free_f GenericIdentifier_free;
asn_struct_print_f GenericIdentifier_print;
asn_constr_check_f GenericIdentifier_constraint;
ber_type_decoder_f GenericIdentifier_decode_ber;
der_type_encoder_f GenericIdentifier_encode_der;
xer_type_decoder_f GenericIdentifier_decode_xer;
xer_type_encoder_f GenericIdentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _GenericIdentifier_H_ */
#include <asn_internal.h>
