/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_GenericNumbers_H_
#define	_GenericNumbers_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GenericNumber.h"
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GenericNumbers */
typedef struct GenericNumbers {
	A_SET_OF(GenericNumber_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GenericNumbers_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GenericNumbers;

#ifdef __cplusplus
}
#endif

#endif	/* _GenericNumbers_H_ */
#include <asn_internal.h>
