/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_GlobalCallReference_H_
#define	_GlobalCallReference_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GlobalCallReference */
typedef OCTET_STRING_t	 GlobalCallReference_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GlobalCallReference;
asn_struct_free_f GlobalCallReference_free;
asn_struct_print_f GlobalCallReference_print;
asn_constr_check_f GlobalCallReference_constraint;
ber_type_decoder_f GlobalCallReference_decode_ber;
der_type_encoder_f GlobalCallReference_encode_der;
xer_type_decoder_f GlobalCallReference_decode_xer;
xer_type_encoder_f GlobalCallReference_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _GlobalCallReference_H_ */
#include <asn_internal.h>
