/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_INServiceCompatibilityResponse_H_
#define	_INServiceCompatibilityResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Entry.h"

#ifdef __cplusplus
extern "C" {
#endif

/* INServiceCompatibilityResponse */
typedef Entry_t	 INServiceCompatibilityResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_INServiceCompatibilityResponse;
asn_struct_free_f INServiceCompatibilityResponse_free;
asn_struct_print_f INServiceCompatibilityResponse_print;
asn_constr_check_f INServiceCompatibilityResponse_constraint;
ber_type_decoder_f INServiceCompatibilityResponse_decode_ber;
der_type_encoder_f INServiceCompatibilityResponse_encode_der;
xer_type_decoder_f INServiceCompatibilityResponse_decode_xer;
xer_type_encoder_f INServiceCompatibilityResponse_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _INServiceCompatibilityResponse_H_ */
#include <asn_internal.h>
