/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_IPAvailable_H_
#define	_IPAvailable_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IPAvailable */
typedef OCTET_STRING_t	 IPAvailable_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IPAvailable;
asn_struct_free_f IPAvailable_free;
asn_struct_print_f IPAvailable_print;
asn_constr_check_f IPAvailable_constraint;
ber_type_decoder_f IPAvailable_decode_ber;
der_type_encoder_f IPAvailable_encode_der;
xer_type_decoder_f IPAvailable_decode_xer;
xer_type_encoder_f IPAvailable_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _IPAvailable_H_ */
#include <asn_internal.h>
