/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_IPRelatedInformation_H_
#define	_IPRelatedInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AlternativeIdentities;

/* IPRelatedInformation */
typedef struct IPRelatedInformation {
	struct AlternativeIdentities	*alternativeCalledPartyIds	/* OPTIONAL */;
	struct AlternativeIdentities	*alternativeOriginatingPartyIds	/* OPTIONAL */;
	struct AlternativeIdentities	*alternativeOriginalCalledPartyIds	/* OPTIONAL */;
	struct AlternativeIdentities	*alternativeRedirectingPartyIds	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IPRelatedInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IPRelatedInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlternativeIdentities.h"

#endif	/* _IPRelatedInformation_H_ */
#include <asn_internal.h>
