/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#include "IPRelatedInformation.h"

static asn_TYPE_member_t asn_MBR_IPRelatedInformation_1[] = {
	{ ATF_POINTER, 4, offsetof(struct IPRelatedInformation, alternativeCalledPartyIds),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AlternativeIdentities,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alternativeCalledPartyIds"
		},
	{ ATF_POINTER, 3, offsetof(struct IPRelatedInformation, alternativeOriginatingPartyIds),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AlternativeIdentities,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alternativeOriginatingPartyIds"
		},
	{ ATF_POINTER, 2, offsetof(struct IPRelatedInformation, alternativeOriginalCalledPartyIds),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AlternativeIdentities,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alternativeOriginalCalledPartyIds"
		},
	{ ATF_POINTER, 1, offsetof(struct IPRelatedInformation, alternativeRedirectingPartyIds),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AlternativeIdentities,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alternativeRedirectingPartyIds"
		},
};
static ber_tlv_tag_t asn_DEF_IPRelatedInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_IPRelatedInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* alternativeCalledPartyIds at 518 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* alternativeOriginatingPartyIds at 519 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* alternativeOriginalCalledPartyIds at 520 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* alternativeRedirectingPartyIds at 521 */
};
static asn_SEQUENCE_specifics_t asn_SPC_IPRelatedInformation_specs_1 = {
	sizeof(struct IPRelatedInformation),
	offsetof(struct IPRelatedInformation, _asn_ctx),
	asn_MAP_IPRelatedInformation_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_IPRelatedInformation = {
	"IPRelatedInformation",
	"IPRelatedInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_IPRelatedInformation_tags_1,
	sizeof(asn_DEF_IPRelatedInformation_tags_1)
		/sizeof(asn_DEF_IPRelatedInformation_tags_1[0]), /* 1 */
	asn_DEF_IPRelatedInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_IPRelatedInformation_tags_1)
		/sizeof(asn_DEF_IPRelatedInformation_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_IPRelatedInformation_1,
	4,	/* Elements count */
	&asn_SPC_IPRelatedInformation_specs_1	/* Additional specs */
};

