/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_ISDNAccessRelatedInformation_H_
#define	_ISDNAccessRelatedInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ISDNAccessRelatedInformation */
typedef OCTET_STRING_t	 ISDNAccessRelatedInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ISDNAccessRelatedInformation;
asn_struct_free_f ISDNAccessRelatedInformation_free;
asn_struct_print_f ISDNAccessRelatedInformation_print;
asn_constr_check_f ISDNAccessRelatedInformation_constraint;
ber_type_decoder_f ISDNAccessRelatedInformation_decode_ber;
der_type_encoder_f ISDNAccessRelatedInformation_encode_der;
xer_type_decoder_f ISDNAccessRelatedInformation_decode_xer;
xer_type_encoder_f ISDNAccessRelatedInformation_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ISDNAccessRelatedInformation_H_ */
#include <asn_internal.h>
