/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_LegID_H_
#define	_LegID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LegType.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LegID_PR {
	LegID_PR_NOTHING,	/* No components present */
	LegID_PR_sendingSideID,
	LegID_PR_receivingSideID
} LegID_PR;

/* LegID */
typedef struct LegID {
	LegID_PR present;
	union LegID_u {
		LegType_t	 sendingSideID;
		LegType_t	 receivingSideID;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LegID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LegID;

#ifdef __cplusplus
}
#endif

#endif	/* _LegID_H_ */
#include <asn_internal.h>
