/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_LegType_H_
#define	_LegType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LegType */
typedef OCTET_STRING_t	 LegType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LegType;
asn_struct_free_f LegType_free;
asn_struct_print_f LegType_print;
asn_constr_check_f LegType_constraint;
ber_type_decoder_f LegType_decode_ber;
der_type_encoder_f LegType_encode_der;
xer_type_decoder_f LegType_decode_xer;
xer_type_encoder_f LegType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _LegType_H_ */
#include <asn_internal.h>
