/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_MinAcceptableATMTrafficDescriptor_H_
#define	_MinAcceptableATMTrafficDescriptor_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MinAcceptableATMTrafficDescriptor */
typedef OCTET_STRING_t	 MinAcceptableATMTrafficDescriptor_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MinAcceptableATMTrafficDescriptor;
asn_struct_free_f MinAcceptableATMTrafficDescriptor_free;
asn_struct_print_f MinAcceptableATMTrafficDescriptor_print;
asn_constr_check_f MinAcceptableATMTrafficDescriptor_constraint;
ber_type_decoder_f MinAcceptableATMTrafficDescriptor_decode_ber;
der_type_encoder_f MinAcceptableATMTrafficDescriptor_encode_der;
xer_type_decoder_f MinAcceptableATMTrafficDescriptor_decode_xer;
xer_type_encoder_f MinAcceptableATMTrafficDescriptor_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MinAcceptableATMTrafficDescriptor_H_ */
#include <asn_internal.h>
