/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#include "Reason.h"

static asn_TYPE_member_t asn_MBR_Reason_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Reason, choice.p_abortCause),
		(ASN_TAG_CLASS_APPLICATION | (10 << 2)),
		0,
		&asn_DEF_P_AbortCause,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"p-abortCause"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Reason, choice.u_abortCause),
		(ASN_TAG_CLASS_APPLICATION | (11 << 2)),
		0,
		&asn_DEF_DialoguePortion,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"u-abortCause"
		},
};
static asn_TYPE_tag2member_t asn_MAP_Reason_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (10 << 2)), 0, 0, 0 }, /* p-abortCause at 92 */
    { (ASN_TAG_CLASS_APPLICATION | (11 << 2)), 1, 0, 0 } /* u-abortCause at 94 */
};
static asn_CHOICE_specifics_t asn_SPC_Reason_specs_1 = {
	sizeof(struct Reason),
	offsetof(struct Reason, _asn_ctx),
	offsetof(struct Reason, present),
	sizeof(((struct Reason *)0)->present),
	asn_MAP_Reason_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Reason = {
	"Reason",
	"Reason",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_Reason_1,
	2,	/* Elements count */
	&asn_SPC_Reason_specs_1	/* Additional specs */
};

