/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_RedirectionInformation_H_
#define	_RedirectionInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RedirectionInformation */
typedef OCTET_STRING_t	 RedirectionInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RedirectionInformation;
asn_struct_free_f RedirectionInformation_free;
asn_struct_print_f RedirectionInformation_print;
asn_constr_check_f RedirectionInformation_constraint;
ber_type_decoder_f RedirectionInformation_decode_ber;
der_type_encoder_f RedirectionInformation_encode_der;
xer_type_decoder_f RedirectionInformation_decode_xer;
xer_type_encoder_f RedirectionInformation_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RedirectionInformation_H_ */
#include <asn_internal.h>
