/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_RedirectingPartyID_H_
#define	_RedirectingPartyID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RedirectingPartyID */
typedef OCTET_STRING_t	 RedirectingPartyID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RedirectingPartyID;
asn_struct_free_f RedirectingPartyID_free;
asn_struct_print_f RedirectingPartyID_print;
asn_constr_check_f RedirectingPartyID_constraint;
ber_type_decoder_f RedirectingPartyID_decode_ber;
der_type_encoder_f RedirectingPartyID_encode_der;
xer_type_decoder_f RedirectingPartyID_decode_xer;
xer_type_encoder_f RedirectingPartyID_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RedirectingPartyID_H_ */
#include <asn_internal.h>
