/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#include "ReturnResult.h"

static asn_TYPE_member_t asn_MBR_resultretres_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct resultretres, opCode),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_OPERATION,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"opCode"
		},
	{ ATF_OPEN_TYPE | ATF_POINTER, 1, offsetof(struct resultretres, parameter),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_Parameter,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"parameter"
		},
};
static ber_tlv_tag_t asn_DEF_resultretres_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_resultretres_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* localValue at 188 */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* globalValue at 189 */
};
static asn_SEQUENCE_specifics_t asn_SPC_resultretres_specs_3 = {
	sizeof(struct resultretres),
	offsetof(struct resultretres, _asn_ctx),
	asn_MAP_resultretres_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_resultretres_3 = {
	"resultretres",
	"resultretres",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_resultretres_tags_3,
	sizeof(asn_DEF_resultretres_tags_3)
		/sizeof(asn_DEF_resultretres_tags_3[0]), /* 1 */
	asn_DEF_resultretres_tags_3,	/* Same as above */
	sizeof(asn_DEF_resultretres_tags_3)
		/sizeof(asn_DEF_resultretres_tags_3[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_resultretres_3,
	2,	/* Elements count */
	&asn_SPC_resultretres_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ReturnResult_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReturnResult, invokeID),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_InvokeIdType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"invokeID"
		},
	{ ATF_POINTER, 1, offsetof(struct ReturnResult, resultretres),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_resultretres_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"resultretres"
		},
};
static ber_tlv_tag_t asn_DEF_ReturnResult_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ReturnResult_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* invokeID at 156 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 } /* resultretres at 158 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ReturnResult_specs_1 = {
	sizeof(struct ReturnResult),
	offsetof(struct ReturnResult, _asn_ctx),
	asn_MAP_ReturnResult_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ReturnResult = {
	"ReturnResult",
	"ReturnResult",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ReturnResult_tags_1,
	sizeof(asn_DEF_ReturnResult_tags_1)
		/sizeof(asn_DEF_ReturnResult_tags_1[0]), /* 1 */
	asn_DEF_ReturnResult_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReturnResult_tags_1)
		/sizeof(asn_DEF_ReturnResult_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ReturnResult_1,
	2,	/* Elements count */
	&asn_SPC_ReturnResult_specs_1	/* Additional specs */
};

