/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_ReturnResult_H_
#define	_ReturnResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InvokeIdType.h"
#include "OPERATION.h"
#include "Parameter.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReturnResult */
typedef struct ReturnResult {
	InvokeIdType_t	 invokeID;
	struct resultretres {
		OPERATION_t	 opCode;
		Parameter_t	*parameter	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *resultretres;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReturnResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReturnResult;

#ifdef __cplusplus
}
#endif

#endif	/* _ReturnResult_H_ */
#include <asn_internal.h>
