/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_ReturnError_H_
#define	_ReturnError_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InvokeIdType.h"
#include "ErrorCode.h"
#include "Parameter.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReturnError */
typedef struct ReturnError {
	InvokeIdType_t	 invokeID;
	ErrorCode_t	 errorCode;
	Parameter_t	*parameter	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReturnError_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReturnError;

#ifdef __cplusplus
}
#endif

#endif	/* _ReturnError_H_ */
#include <asn_internal.h>
