/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_RouteList_H_
#define	_RouteList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Route.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RouteList */
typedef struct RouteList {
	A_SEQUENCE_OF(Route_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RouteList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RouteList;

#ifdef __cplusplus
}
#endif

#endif	/* _RouteList_H_ */
#include <asn_internal.h>
