/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_Route_H_
#define	_Route_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Route */
typedef OCTET_STRING_t	 Route_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Route;
asn_struct_free_f Route_free;
asn_struct_print_f Route_print;
asn_constr_check_f Route_constraint;
ber_type_decoder_f Route_decode_ber;
der_type_encoder_f Route_encode_der;
xer_type_decoder_f Route_decode_xer;
xer_type_encoder_f Route_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Route_H_ */
#include <asn_internal.h>
