/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_ScfID_H_
#define	_ScfID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ScfID */
typedef OCTET_STRING_t	 ScfID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScfID;
asn_struct_free_f ScfID_free;
asn_struct_print_f ScfID_print;
asn_constr_check_f ScfID_constraint;
ber_type_decoder_f ScfID_decode_ber;
der_type_encoder_f ScfID_encode_der;
xer_type_decoder_f ScfID_decode_xer;
xer_type_encoder_f ScfID_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ScfID_H_ */
#include <asn_internal.h>
