/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#include "ServiceInteractionIndicatorsTwo.h"

static asn_TYPE_member_t asn_MBR_redirectServiceTreatmentInd_14[] = {
	{ ATF_POINTER, 1, offsetof(struct redirectServiceTreatmentInd, redirectReason),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RedirectReason,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"redirectReason"
		},
};
static ber_tlv_tag_t asn_DEF_redirectServiceTreatmentInd_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_redirectServiceTreatmentInd_tag2el_14[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* redirectReason at 434 */
};
static asn_SEQUENCE_specifics_t asn_SPC_redirectServiceTreatmentInd_specs_14 = {
	sizeof(struct redirectServiceTreatmentInd),
	offsetof(struct redirectServiceTreatmentInd, _asn_ctx),
	asn_MAP_redirectServiceTreatmentInd_tag2el_14,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	0,	/* Start extensions */
	2	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_redirectServiceTreatmentInd_14 = {
	"redirectServiceTreatmentInd",
	"redirectServiceTreatmentInd",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_redirectServiceTreatmentInd_tags_14,
	sizeof(asn_DEF_redirectServiceTreatmentInd_tags_14)
		/sizeof(asn_DEF_redirectServiceTreatmentInd_tags_14[0]), /* 2 */
	asn_DEF_redirectServiceTreatmentInd_tags_14,	/* Same as above */
	sizeof(asn_DEF_redirectServiceTreatmentInd_tags_14)
		/sizeof(asn_DEF_redirectServiceTreatmentInd_tags_14[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_redirectServiceTreatmentInd_14,
	1,	/* Elements count */
	&asn_SPC_redirectServiceTreatmentInd_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ServiceInteractionIndicatorsTwo_1[] = {
	{ ATF_POINTER, 14, offsetof(struct ServiceInteractionIndicatorsTwo, forwardServiceInteractionInd),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ForwardServiceInteractionInd,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"forwardServiceInteractionInd"
		},
	{ ATF_POINTER, 13, offsetof(struct ServiceInteractionIndicatorsTwo, backwardServiceInteractionInd),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_BackwardServiceInteractionInd,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"backwardServiceInteractionInd"
		},
	{ ATF_POINTER, 12, offsetof(struct ServiceInteractionIndicatorsTwo, bothwayThroughConnectionInd),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_BothwayThroughConnectionInd,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bothwayThroughConnectionInd"
		},
	{ ATF_POINTER, 11, offsetof(struct ServiceInteractionIndicatorsTwo, suspendTimer),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SuspendTimer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"suspendTimer"
		},
	{ ATF_POINTER, 10, offsetof(struct ServiceInteractionIndicatorsTwo, connectedNumberTreatmentInd),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ConnectedNumberTreatmentInd,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"connectedNumberTreatmentInd"
		},
	{ ATF_POINTER, 9, offsetof(struct ServiceInteractionIndicatorsTwo, suppressCallDiversionNotification),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"suppressCallDiversionNotification"
		},
	{ ATF_POINTER, 8, offsetof(struct ServiceInteractionIndicatorsTwo, suppressCallTransferNotification),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"suppressCallTransferNotification"
		},
	{ ATF_POINTER, 7, offsetof(struct ServiceInteractionIndicatorsTwo, allowCdINNoPresentationInd),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"allowCdINNoPresentationInd"
		},
	{ ATF_POINTER, 6, offsetof(struct ServiceInteractionIndicatorsTwo, userDialogueDurationInd),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"userDialogueDurationInd"
		},
	{ ATF_POINTER, 5, offsetof(struct ServiceInteractionIndicatorsTwo, overrideLineRestrictions),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"overrideLineRestrictions"
		},
	{ ATF_POINTER, 4, offsetof(struct ServiceInteractionIndicatorsTwo, suppressVPNAPP),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"suppressVPNAPP"
		},
	{ ATF_POINTER, 3, offsetof(struct ServiceInteractionIndicatorsTwo, calledINNumberOverriding),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"calledINNumberOverriding"
		},
	{ ATF_POINTER, 2, offsetof(struct ServiceInteractionIndicatorsTwo, redirectServiceTreatmentInd),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		0,
		&asn_DEF_redirectServiceTreatmentInd_14,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"redirectServiceTreatmentInd"
		},
	{ ATF_POINTER, 1, offsetof(struct ServiceInteractionIndicatorsTwo, nonCUGCall),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nonCUGCall"
		},
};
static ber_tlv_tag_t asn_DEF_ServiceInteractionIndicatorsTwo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ServiceInteractionIndicatorsTwo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* forwardServiceInteractionInd at 387 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* backwardServiceInteractionInd at 390 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* bothwayThroughConnectionInd at 392 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* suspendTimer at 394 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* connectedNumberTreatmentInd at 396 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* suppressCallDiversionNotification at 398 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* suppressCallTransferNotification at 400 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* allowCdINNoPresentationInd at 402 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* userDialogueDurationInd at 407 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* overrideLineRestrictions at 412 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* suppressVPNAPP at 419 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* calledINNumberOverriding at 426 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* redirectServiceTreatmentInd at 434 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 } /* nonCUGCall at 447 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ServiceInteractionIndicatorsTwo_specs_1 = {
	sizeof(struct ServiceInteractionIndicatorsTwo),
	offsetof(struct ServiceInteractionIndicatorsTwo, _asn_ctx),
	asn_MAP_ServiceInteractionIndicatorsTwo_tag2el_1,
	14,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	13,	/* Start extensions */
	15	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ServiceInteractionIndicatorsTwo = {
	"ServiceInteractionIndicatorsTwo",
	"ServiceInteractionIndicatorsTwo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ServiceInteractionIndicatorsTwo_tags_1,
	sizeof(asn_DEF_ServiceInteractionIndicatorsTwo_tags_1)
		/sizeof(asn_DEF_ServiceInteractionIndicatorsTwo_tags_1[0]), /* 1 */
	asn_DEF_ServiceInteractionIndicatorsTwo_tags_1,	/* Same as above */
	sizeof(asn_DEF_ServiceInteractionIndicatorsTwo_tags_1)
		/sizeof(asn_DEF_ServiceInteractionIndicatorsTwo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ServiceInteractionIndicatorsTwo_1,
	14,	/* Elements count */
	&asn_SPC_ServiceInteractionIndicatorsTwo_specs_1	/* Additional specs */
};

