/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_ServiceProfileIdentifier_H_
#define	_ServiceProfileIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ServiceProfileIdentifier */
typedef OCTET_STRING_t	 ServiceProfileIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceProfileIdentifier;
asn_struct_free_f ServiceProfileIdentifier_free;
asn_struct_print_f ServiceProfileIdentifier_print;
asn_constr_check_f ServiceProfileIdentifier_constraint;
ber_type_decoder_f ServiceProfileIdentifier_decode_ber;
der_type_encoder_f ServiceProfileIdentifier_encode_der;
xer_type_decoder_f ServiceProfileIdentifier_decode_xer;
xer_type_encoder_f ServiceProfileIdentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceProfileIdentifier_H_ */
#include <asn_internal.h>
