/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_SuspendTimer_H_
#define	_SuspendTimer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SuspendTimer */
typedef long	 SuspendTimer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SuspendTimer;
asn_struct_free_f SuspendTimer_free;
asn_struct_print_f SuspendTimer_print;
asn_constr_check_f SuspendTimer_constraint;
ber_type_decoder_f SuspendTimer_decode_ber;
der_type_encoder_f SuspendTimer_encode_der;
xer_type_decoder_f SuspendTimer_decode_xer;
xer_type_encoder_f SuspendTimer_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SuspendTimer_H_ */
#include <asn_internal.h>
