/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#include "TriggerType.h"

int
TriggerType_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_ENUMERATED.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static void
TriggerType_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_ENUMERATED.free_struct;
	td->print_struct   = asn_DEF_ENUMERATED.print_struct;
	td->ber_decoder    = asn_DEF_ENUMERATED.ber_decoder;
	td->der_encoder    = asn_DEF_ENUMERATED.der_encoder;
	td->xer_decoder    = asn_DEF_ENUMERATED.xer_decoder;
	td->xer_encoder    = asn_DEF_ENUMERATED.xer_encoder;
	td->uper_decoder   = asn_DEF_ENUMERATED.uper_decoder;
	td->uper_encoder   = asn_DEF_ENUMERATED.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_ENUMERATED.per_constraints;
	td->elements       = asn_DEF_ENUMERATED.elements;
	td->elements_count = asn_DEF_ENUMERATED.elements_count;
     /* td->specifics      = asn_DEF_ENUMERATED.specifics;	// Defined explicitly */
}

void
TriggerType_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	TriggerType_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
TriggerType_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	TriggerType_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
TriggerType_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	TriggerType_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
TriggerType_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	TriggerType_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
TriggerType_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	TriggerType_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
TriggerType_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	TriggerType_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_INTEGER_enum_map_t asn_MAP_TriggerType_value2enum_1[] = {
	{ 0,	17,	"featureActivation" },
	{ 1,	19,	"verticalServiceCode" },
	{ 2,	16,	"customizedAccess" },
	{ 3,	18,	"customizedIntercom" },
	{ 12,	16,	"emergencyService" },
	{ 13,	3,	"aFR" },
	{ 14,	13,	"sharedIOTrunk" },
	{ 17,	12,	"offHookDelay" },
	{ 18,	15,	"channelSetupPRI" },
	{ 25,	9,	"tNoAnswer" },
	{ 26,	5,	"tBusy" },
	{ 27,	16,	"oCalledPartyBusy" },
	{ 29,	9,	"oNoAnswer" },
	{ 30,	28,	"originationAttemptAuthorized" },
	{ 31,	7,	"oAnswer" },
	{ 32,	11,	"oDisconnect" },
	{ 33,	21,	"termAttemptAuthorized" },
	{ 34,	7,	"tAnswer" },
	{ 35,	11,	"tDisconnect" },
	{ 100,	14,	"oModifyRequest" },
	{ 101,	14,	"tModifyRequest" }
};
static unsigned int asn_MAP_TriggerType_enum2value_1[] = {
	5,	/* aFR(13) */
	8,	/* channelSetupPRI(18) */
	2,	/* customizedAccess(2) */
	3,	/* customizedIntercom(3) */
	4,	/* emergencyService(12) */
	0,	/* featureActivation(0) */
	14,	/* oAnswer(31) */
	11,	/* oCalledPartyBusy(27) */
	15,	/* oDisconnect(32) */
	19,	/* oModifyRequest(100) */
	12,	/* oNoAnswer(29) */
	7,	/* offHookDelay(17) */
	13,	/* originationAttemptAuthorized(30) */
	6,	/* sharedIOTrunk(14) */
	17,	/* tAnswer(34) */
	10,	/* tBusy(26) */
	18,	/* tDisconnect(35) */
	20,	/* tModifyRequest(101) */
	9,	/* tNoAnswer(25) */
	16,	/* termAttemptAuthorized(33) */
	1	/* verticalServiceCode(1) */
};
static asn_INTEGER_specifics_t asn_SPC_TriggerType_specs_1 = {
	asn_MAP_TriggerType_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_TriggerType_enum2value_1,	/* N => "tag"; sorted by N */
	21,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_TriggerType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_TriggerType = {
	"TriggerType",
	"TriggerType",
	TriggerType_free,
	TriggerType_print,
	TriggerType_constraint,
	TriggerType_decode_ber,
	TriggerType_encode_der,
	TriggerType_decode_xer,
	TriggerType_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TriggerType_tags_1,
	sizeof(asn_DEF_TriggerType_tags_1)
		/sizeof(asn_DEF_TriggerType_tags_1[0]), /* 1 */
	asn_DEF_TriggerType_tags_1,	/* Same as above */
	sizeof(asn_DEF_TriggerType_tags_1)
		/sizeof(asn_DEF_TriggerType_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_TriggerType_specs_1	/* Additional specs */
};

