/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn1/tcap.asn"
 */

#ifndef	_TriggerType_H_
#define	_TriggerType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TriggerType {
	TriggerType_featureActivation	= 0,
	TriggerType_verticalServiceCode	= 1,
	TriggerType_customizedAccess	= 2,
	TriggerType_customizedIntercom	= 3,
	TriggerType_emergencyService	= 12,
	TriggerType_aFR	= 13,
	TriggerType_sharedIOTrunk	= 14,
	TriggerType_offHookDelay	= 17,
	TriggerType_channelSetupPRI	= 18,
	TriggerType_tNoAnswer	= 25,
	TriggerType_tBusy	= 26,
	TriggerType_oCalledPartyBusy	= 27,
	TriggerType_oNoAnswer	= 29,
	TriggerType_originationAttemptAuthorized	= 30,
	TriggerType_oAnswer	= 31,
	TriggerType_oDisconnect	= 32,
	TriggerType_termAttemptAuthorized	= 33,
	TriggerType_tAnswer	= 34,
	TriggerType_tDisconnect	= 35,
	TriggerType_oModifyRequest	= 100,
	TriggerType_tModifyRequest	= 101
} e_TriggerType;

/* TriggerType */
typedef ENUMERATED_t	 TriggerType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TriggerType;
asn_struct_free_f TriggerType_free;
asn_struct_print_f TriggerType_print;
asn_constr_check_f TriggerType_constraint;
ber_type_decoder_f TriggerType_decode_ber;
der_type_encoder_f TriggerType_encode_der;
xer_type_decoder_f TriggerType_decode_xer;
xer_type_encoder_f TriggerType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TriggerType_H_ */
#include <asn_internal.h>
