.PHONY: all lib clean lib-clean

LIBNAME=libtcap-asn.a

CFLAGS=-g -Wall -O3 -fPIC

lib: $(LIBNAME)

include Makefile.am.sample

LIB_OBJS=${ASN_MODULE_SOURCES:.c=.o}

$(LIBNAME): $(LIB_OBJS)
	ar cr $(LIBNAME) $(LIB_OBJS)

lib-clean: clean
	rm -f $(LIBNAME)
