name: Cppcheck

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Get tool
        run: sudo apt-get install -q -y --no-install-recommends cppcheck

      - name: Analyze
        run: cppcheck -q --enable=all src
